# Generated by Django 4.1.7 on 2023-03-02 07:37

from django.db import migrations, models
import myapp1.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="service_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=50)),
                ("sdesc", models.CharField(max_length=50)),
                ("sdetails", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="record_model",
            name="cemail",
            field=models.CharField(
                max_length=50, validators=[myapp1.models.check_space]
            ),
        ),
        migrations.AlterField(
            model_name="record_model",
            name="cmessage",
            field=models.TextField(validators=[myapp1.models.check_space]),
        ),
        migrations.AlterField(
            model_name="record_model",
            name="cname",
            field=models.CharField(
                max_length=50, validators=[myapp1.models.check_space]
            ),
        ),
        migrations.AlterField(
            model_name="record_model",
            name="cphone",
            field=models.CharField(
                max_length=50, validators=[myapp1.models.check_space]
            ),
        ),
        migrations.AlterField(
            model_name="record_model",
            name="cservice",
            field=models.CharField(
                max_length=50, validators=[myapp1.models.check_space]
            ),
        ),
    ]
