# Generated by Django 4.1.7 on 2023-03-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0004_alter_service_info_simage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service_info",
            name="simage",
            field=models.ImageField(default="", upload_to="myapp1/static/images"),
        ),
    ]
